import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { PGlite } from '@electric-sql/pglite';

test('PostgreSQL migration, RLS, idempotent sync, recovery and notification leases', async t => {
  const db = new PGlite();
  t.after(()=>db.close());
  await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
    create schema auth; create table auth.users(id uuid primary key);
    create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
    grant usage on schema auth,public to anon,authenticated,service_role;
    grant execute on function auth.uid() to anon,authenticated,service_role;`);
  await db.exec(await readFile(new URL('../supabase/setup.sql',import.meta.url),'utf8'));
  const upgrade=await readFile(new URL('../supabase/upgrade-v5.sql',import.meta.url),'utf8');
  await db.exec(upgrade); await db.exec(upgrade);
  const users=[1,2,3,4].map(n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0'));
  for(const id of users) await db.query('insert into auth.users(id) values($1)',[id]);
  const login=async id=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');};
  await login(users[0]);
  const pair=(await db.query("select * from public.create_pair('Ahmet')")).rows[0];
  await login(users[1]); await db.query("select * from public.join_pair($1,'Arkadaş')",[pair.invite_code]);
  await login(users[2]);
  await assert.rejects(db.query("select * from public.join_pair($1,'Üçüncü')",[pair.invite_code]),/iki kişi/);
  assert.equal((await db.query('select * from public.water_entries')).rows.length,0);
  const change=(kind,revision)=>({kind,revision,client_id:'entry',amount:375,recorded_at:'2026-09-12T21:01:00Z',recorded_day:'2026-09-13'});
  const sync=changes=>db.query('select * from public.sync_water_changes($1,$2::jsonb)',[pair.room_id,JSON.stringify(changes)]);
  await assert.rejects(sync([change('upsert',1)]),/oturumu/);
  await login(users[0]);
  await sync([change('upsert',1)]); await sync([change('upsert',1)]);
  assert.equal((await db.query('select * from public.water_entries')).rows.length,1);
  await sync([change('delete',3)]); await sync([change('upsert',2)]);
  assert.equal((await db.query('select * from public.water_entries')).rows.length,0);
  await sync([change('upsert',4)]);
  assert.equal((await db.query("select * from public.get_pair_entries('2026-09-13','2026-09-13','Europe/Istanbul')")).rows[0].amount,375);
  await assert.rejects(db.query('select * from private.recovery_codes'),/permission denied/);
  await assert.rejects(db.query('select * from public.claim_push_job()'),/permission denied/);
  await login(users[1]);
  assert.equal((await db.query('select * from public.water_entries')).rows.length,1);
  await db.query("insert into public.push_subscriptions(user_id,endpoint,p256dh,auth) values($1,'https://web.push.apple.com/test','p','a')",[users[1]]);
  assert.equal((await db.query('select notifications_enabled from public.profiles where user_id=$1',[users[1]])).rows[0].notifications_enabled,true);
  await login(users[0]);
  const job=(await db.query('insert into public.notification_jobs(room_id,sender_user_id,recipient_user_id) values($1,$2,$3) returning *',[pair.room_id,users[0],users[1]])).rows[0];
  await assert.rejects(db.query('insert into public.notification_jobs(room_id,sender_user_id,recipient_user_id) values($1,$2,$3)',[pair.room_id,users[0],users[1]]),/30 saniye/);
  await db.exec('reset role; set role service_role');
  const claim=()=>db.query('select * from public.claim_push_job($1)',[job.id]);
  assert.equal((await claim()).rows[0].attempts,1); assert.equal((await claim()).rows.length,0);
  await db.query('select public.finish_push_job($1,1,false,$2,true)',[job.id,'push_503']);
  assert.equal((await claim()).rows.length,0);
  await db.exec('reset role'); await db.query("update public.notification_jobs set next_attempt_at=now()-interval '1 second' where id=$1",[job.id]);
  await db.exec('set role service_role'); assert.equal((await claim()).rows[0].attempts,2);
  await db.query('select public.finish_push_job($1,1,true)',[job.id]); // stale worker must not finish attempt 2
  await db.exec('reset role'); assert.equal((await db.query('select status from public.notification_jobs where id=$1',[job.id])).rows[0].status,'processing');
  await db.exec('set role service_role'); await db.query('select public.finish_push_job($1,2,true)',[job.id]);
  assert.equal((await claim()).rows.length,0);
  await login(users[0]);
  const code='A'.repeat(64), hash=createHash('sha256').update(code).digest('hex');
  await db.query('select public.set_recovery_code($1)',[hash]);
  await login(users[3]);
  const recovered=(await db.query('select * from public.recover_pair($1)',[code])).rows[0];
  assert.equal(recovered.room_id,pair.room_id); assert.equal(recovered.user_id,users[3]);
  assert.equal((await db.query('select * from public.water_entries')).rows[0].user_id,users[3]);
  await assert.rejects(db.query('select * from public.recover_pair($1)',[code]),/geçersiz veya kullanılmış/);
  await login(users[0]); assert.equal((await db.query('select * from public.water_entries')).rows.length,0);
  await assert.rejects(sync([change('upsert',10)]),/oturumu/);
  await login(users[1]); assert.equal((await db.query('select * from public.current_pair()')).rows[0].room_id,pair.room_id);
});
