import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { build } from 'esbuild';
import { Window } from 'happy-dom';

test('UI starts offline, validates forms, separates edit/add, lists all records and closes empty dialogs',async t=>{
  const window=new Window({url:'https://su.test',settings:{disableJavaScriptFileLoading:true,disableCSSFileLoading:true}});
  window.structuredClone=structuredClone;
  t.after(async()=>{await window.happyDOM.abort();window.close();});
  const html=await readFile(new URL('../index.html',import.meta.url),'utf8');
  window.document.write(html.replace(/<script[\s\S]*?<\/script>/g,''));
  window.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};
  window.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');this.dispatchEvent(new window.Event('close'));};
  Object.defineProperty(window.navigator,'onLine',{value:false,configurable:true});
  window.fetch=()=>{throw new Error('Offline startup must not fetch');};
  const bundle=await build({entryPoints:[new URL('../src/app.js',import.meta.url).pathname],bundle:true,write:false,format:'iife',target:'es2020'});
  window.eval(bundle.outputFiles[0].text);
  const $=id=>window.document.getElementById(id);
  const tap=selector=>window.document.querySelector(selector).click();
  const submit=id=>$(id).dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));
  const settle=()=>new Promise(r=>setTimeout(r,180));
  assert.equal(window.SU_READY,true);assert.equal($('total-number').textContent,'0');
  tap('[data-custom-new]');assert.equal($('custom-dialog').hasAttribute('open'),true);
  tap('[data-close="custom-dialog"]');await settle();assert.equal($('custom-dialog').hasAttribute('open'),false);
  tap('[data-custom-new]');$('custom-input').value='3001';submit('custom-form');
  assert.ok($('custom-error').textContent);assert.equal($('total-number').textContent,'0');
  $('custom-input').value='375';submit('custom-form');await settle();assert.equal($('total-number').textContent,'375',$('custom-error').textContent);
  tap('[data-custom-edit]');$('custom-input').value='420';submit('custom-form');await settle();assert.equal($('total-number').textContent,'375');
  tap('[data-custom-add]');assert.equal($('total-number').textContent,'795');
  for(let i=0;i<5;i++)tap('[data-amount="100"]');
  assert.equal($('entry-content').querySelectorAll('li').length,5);
  tap('#all-records');assert.equal($('history-entries').querySelectorAll('li').length,7);
  const todayTotal = $('total-number').textContent;
  const rememberedCustom = JSON.parse(window.localStorage.getItem('su:data:v5')).settings.customAmount;
  tap('#history-previous'); const selectedDay = $('history-date').value;
  tap('#history-add'); assert.equal($('record-form').dataset.day, selectedDay);
  $('record-amount').value = '10001'; submit('record-form'); assert.ok($('record-error').textContent);
  $('record-amount').value = '2500'; submit('record-form'); submit('record-form'); await settle();
  assert.equal($('history-total').textContent, '2.500 ml');
  assert.equal($('history-entries').querySelectorAll('li').length, 1);
  assert.equal($('total-number').textContent, todayTotal);
  assert.equal($('toast').parentElement.id, 'history-dialog');
  assert.equal($('history-entries').querySelector('time').textContent, 'Sonradan');
  const entryId = $('history-entries').querySelector('li').dataset.id;
  tap('#history-entries .edit-entry'); assert.equal($('record-amount').value, '2500');
  $('record-amount').value = '1800'; submit('record-form'); await settle();
  assert.equal($('history-total').textContent, '1.800 ml');
  assert.equal($('history-entries').querySelector('li').dataset.id, entryId);
  tap('#toast-action'); assert.equal($('history-total').textContent, '2.500 ml');
  tap('#history-entries .edit-entry'); $('record-amount').value='';tap('[data-close="record-dialog"]');await settle();
  assert.equal($('record-dialog').hasAttribute('open'),false);assert.equal($('history-total').textContent,'2.500 ml');
  const saved=JSON.parse(window.localStorage.getItem('su:data:v5'));
  assert.equal(saved.entries.find(entry=>entry.clientId===entryId).day,selectedDay);
  assert.equal(saved.settings.customAmount,rememberedCustom);
  tap('[data-close="history-dialog"]');await settle();
  tap('#settings-button');assert.equal($('settings-dialog').hasAttribute('open'),true);
  $('goal-input').value='0';submit('settings-form');assert.ok($('settings-error').textContent);
  $('goal-input').value='2500';window.document.querySelector('[name="palette"][value="olive"]').checked=true;submit('settings-form');
  assert.equal(window.document.documentElement.dataset.palette,'olive');
  assert.equal(JSON.parse(window.localStorage.getItem('su:data:v5')).settings.customAmount,420);
});
